---
title: "exploratory"
author: "Cam Reimer"
date: "2023-09-26"
output: html_document
---

```{r, INIT}
#load in packages 
library(tidyverse)
library(lubridate)
library(dplyr)
library(corrplot)
library(mediation)

#load in data
load("C:/Users/camer/OneDrive/Documents/SPH/PRESTO/data/data_processed.RData")
load("C:/Users/camer/OneDrive/Documents/SPH/PRESTO/data/dropped.RData")
```

```{r, Mediation Analysis}
data <- imputed
med_fit <- lm(b_totalmet ~ ndvi_100_smax_iqr + ageatqstn + b_race_ethnic_census + b_educ + b_income + ct_HHinc + ct_lths , data = data)
pss_fit <- lm(pss_score ~ ndvi_100_smax_iqr + ageatqstn + b_race_ethnic_census + b_educ + b_income + b_totalmet + ct_HHinc + ct_lths , data = data)

med_out_pss <- mediate(med_fit, pss_fit, 
                   treat = "ndvi_100_smax_iqr", 
                   mediator = "b_totalmet", 
                   sims = 100, 
                   treat.value = quantile(data$ndvi_100_smax_iqr, 0.75),
                   control.value = quantile(data$ndvi_100_smax_iqr, 0.25))
summary(med_out_pss)
plot(med_out_pss)

mdi_fit <- lm(b_mdi_score ~ ndvi_100_smax_iqr + ageatqstn + b_race_ethnic_census + b_educ + b_income + b_totalmet + ct_HHinc + ct_lths , data = data)
med_out_mdi <- mediate(med_fit, mdi_fit, 
                   treat = "ndvi_100_smax_iqr", 
                   mediator = "b_totalmet", 
                   sims = 100, 
                   treat.value = quantile(data$ndvi_100_smax_iqr, 0.75),
                   control.value = quantile(data$ndvi_100_smax_iqr, 0.25))
summary(med_out_mdi)
plot(med_out_mdi)
```

```{r, DEMOGRAPHIC}
# States and Provinces
all <- sort(unique(imputed$state))
provinces <- c('AB', 'BC', 'MB', 'NB', 'NL', 'NT', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT')

CAD <- provinces[provinces %in% all]
CAD # All provinces and 2 territories (not Nunavut)
length(CAD)

USA <- all[!(all %in% provinces)]
USA #All states + DC, except for AK and HI
length(USA)

counts <- imputed |> dplyr::select(Country, state) |> count(state, Country)
write.csv(counts, "C:/Users/camer/OneDrive/Documents/SPH/PRESTO/map_counts.csv")

### Income 
#% of participants with income >$50,000
(sum(as.numeric(imputed$b_income) >= 4) / nrow(imputed)) * 100

#% w/ income >$50,000 for dropped participants
(sum(as.numeric(imputed$b_income) >= 4, na.rm = TRUE) / length(na.omit(imputed_dropped$b_income))) * 100
```

```{r, NDVI CORRELATIONS}
# Get NDVI columns
all_n <- dplyr::select(imputed, matches('ndvi', ignore.case = 'quantile')) |>
    dplyr::select(!matches('quantile'))
n <- dplyr::select(all_n, !matches('iqr'))
iqr <- dplyr::select(all_n, matches('iqr'))

# Rename columns
cnames <- paste0( c(rep('Annual max', 4), rep('Sesonal max', 4), rep('Sesonal mean', 4)), ' ', rep(c('50m', '100m', '250m', '500m'), 3))
colnames(n) <- cnames
colnames(iqr) <- cnames

dat <- n
m <- round(cor(dat, method = "spearman"), 2)

write.csv(m,"C:/Users/camer/OneDrive/Documents/SPH/PRESTO/supplementary/NDVIcorrelations.csv" )
```

```{r NDVI exposures}
library(ggplot2)
library(ggridges)


tmp_dat <- matrix(c(imputed$ndvi_100_amax, imputed$ndvi_100_smax, imputed$ndvi_100_smean), ncol = 1) |> as.data.frame()
tmp_dat$name <- c(rep("Annual Max", 9718), rep("Seasonal Max", 9718), rep("Seasonal Mean", 9718))

ggplot(tmp_dat, aes(x = V1, y = name, fill = name, alpha = 0.8)) + 
  geom_density_ridges(rel_min_height = 0.001, scale = 1.5) + 
  coord_cartesian(clip = "off") +
  theme_ridges() + 
  theme(legend.position = "none")

tmp_dat <- matrix(c(imputed$ndvi_100_smean, urban$ndvi_100_smean, rural$ndvi_100_smean), ncol = 1) |> as.data.frame()
tmp_dat$name <- c(rep("Full Sample", 9718), rep("Urban", 7012), rep("Rural", 2706))

ggplot(tmp_dat, aes(x = V1, y = name, fill = name, alpha = 0.8)) + 
  geom_density_ridges(rel_min_height = 0.001, scale = 1.5) + 
  coord_cartesian(clip = "off") +
  theme_ridges() + 
  theme(legend.position = "none")


d1 <- density(imputed$ndvi_100_amax)
d2 <- density(imputed$ndvi_100_smax)
d3 <- density(imputed$ndvi_100_smean)
plot(d1, col = 2, lwd = 2, main = "NDVI distributions - Full Sample")
lines(d2, col = 3, lwd = 2)
lines(d3, col = 4, lwd = 2)
legend("topleft", legend = c("Annual Max", "Seasonal Max", "Seasonal Mean"), col = c(2, 3, 4), lwd = 2, lty = 1)

d1 <- density(imputed$ndvi_100_smean)
d2 <- density(urban$ndvi_100_smean)
d3 <- density(rural$ndvi_100_smean)
plot(d1, col = 2, lwd = 2, main = "NDVI distributions - Seasonal Mean")
lines(d2, col = 3, lwd = 2)
lines(d3, col = 4, lwd = 2)
legend("topleft", legend = c("Full Sample", "Urban", "Rural"), col = c(2, 3, 4), lwd = 2, lty = 1)

mean(urban$ndvi_100_smean)
sd(urban$ndvi_100_smean)

mean(rural$ndvi_100_smean)
sd(rural$ndvi_100_smean)


```

```{r}
# Estimates and CI for select models

### FILTER TO ONLY MODELS INCLUDED IN THE MANUSCRIPT

source("analysis_functions.R")
x <- c("ageatqstn", "b_race_ethnic_census", "season", "b_educ", "b_income", "ct_HHinc", "ct_lths")

# Full sample - PSS model 1 
ma <- lmfull_processed(data = imputed, y = 'pss_score', buffers = 100, x = x[1:3], ndvi_measure = 'smean', sig_figs = 2)
ma

mb <- lmfull_processed(data = imputed, y = 'pss_score', buffers = 100, x = x[1:3], ndvi_measure = 'smean', sig_figs = 2)
mb

x <- c("ageatqstn", "b_race_ethnic_census", "season", "b_educ", "b_income", "ct_lths") 

# NSES1 - urban
m1 <- lmfull_processed(data = NSES1_urban, y = 'pss_score', buffers = 100, x = x, ndvi_measure = 'smean', sig_figs = 2 )
m1

# NSES2 - urban 
m2 <- lmfull_processed(data = NSES2_urban, y = 'pss_score', buffers = 100, x = x, ndvi_measure = 'smean', sig_figs = 2 )
m2

# NSES3 - rural
m3 <- lmfull_processed(data = NSES3_rural, y = 'pss_score', buffers = 500, x = x, ndvi_measure = 'smean', sig_figs = 2 )
m3

```

```{r}
### REPEAT w/ MDI 
# Full sample - model 1 
x <- c("ageatqstn", "b_race_ethnic_census", "season", "b_educ", "b_income", "ct_HHinc", "ct_lths")

ma <- lmfull_processed(data = imputed, y = 'b_mdi_score', buffers = 100, x = x[1:3], ndvi_measure = 'smean', sig_figs = 2)
ma

mb <- lmfull_processed(data = imputed, y = 'b_mdi_score', buffers = 100, x = x[1:3], ndvi_measure = 'smean', sig_figs = 2)
mb

x <- c("ageatqstn", "b_race_ethnic_census", "season", "b_educ", "b_income", "ct_lths") 

# NSES1 - urban
m1 <- lmfull_processed(data = NSES1_urban, y = 'b_mdi_score', buffers = 100, x = x, ndvi_measure = 'smean', sig_figs = 2 )
m1

# NSES2 - urban 
m2 <- lmfull_processed(data = NSES2_urban, y = 'b_mdi_score', buffers = 100, x = x, ndvi_measure = 'smean', sig_figs = 2 )
m2

# NSES3 - rural
m3 <- lmfull_processed(data = NSES3_rural, y = 'b_mdi_score', buffers = 500, x = x, ndvi_measure = 'smean', sig_figs = 2 )
m3
```