---
title: "figure1"
author: "Cam Reimer"
date: "2/4/2023"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
library(lubridate)
library(dplyr)
library(tidyr)

source("analysis_functions.R")
load("C:/Users/camer/OneDrive/Documents/SPH/PRESTO/data/data_processed.RData")
```

```{r, Run Models}
############# INPUTS ###########################################################
ndvi_measure <- "amax"  # CHANGE TO "smax" or "smean" to explore other NDVI measures
outcome = "pss_score"   # CHANGE OUTCOME to "b_mdi_score" to recreate figure 2
iqr = TRUE              # Use NDVI IQR?
out_dir <- "C:/Users/camer/OneDrive/Documents/SPH/PRESTO/figures/"        # Directory to save output figure
sup_dir <- "C:/Users/camer/OneDrive/Documents/SPH/PRESTO/supplementary/"  # Directory to save figure for supplement
################################################################################

# Set up model runs 
x <- c("ageatqstn", "b_race_ethnic_census", "b_educ", "b_income", "b_totalmet", "ct_lths") #Model 3 (without ct_HHinc)
buffers <- c(50, 100, 250, 500)
datasets <- list(NSES1, NSES2, NSES3, NSES1_urban, NSES2_urban,NSES3_urban, NSES1_rural, NSES2_rural, NSES3_rural)
figure1 <- as.data.frame(matrix(nrow=1, ncol=3))
colnames(figure1) <- c("Mean", "Lower_CI", "Upper_CI")

# Run models with stratified data sets 
for(i in 1:length(datasets)){
  tmp <- lmfull(data=datasets[[i]], y=outcome, buffers=buffers, x=x, ndvi_measure=ndvi_measure, iqr = iqr)$results
  figure1 <- rbind(figure1, tmp)
  rm(tmp)
}
figure1 <- na.omit(figure1)
```

```{r, Group Results}
# add group categories 
figure1$buffer <- rep(c("50m", "100m", "250m", "500m"), 9)
figure1$sample <- c(rep("Full", 12), rep("Urban", 12), rep("Non-Urban", 12))
figure1$quantile <- rep(c(rep("Low NSES", 4), rep("Medium NSES",4), rep("High NSES",4)),3) 

# factorize
figure1$buffer <- factor(figure1$buffer, levels = c("50m", "100m", "250m", "500m"))
figure1$quantile <- factor(figure1$quantile, levels = c("Low NSES", "Medium NSES", "High NSES"))
```

```{r, Plot}
pd = position_dodge(.6)    # How much to jitter the points on the plot

ggplot(data=figure1, aes(x = buffer, y = Mean, color=quantile))+
  geom_line(aes(linetype = quantile), linewidth=0.5, position = pd)+
  geom_point(aes(colour = factor(quantile)), size=2.5, position = pd)+
  geom_errorbar(aes(ymin=Lower_CI, ymax=Upper_CI, linetype=quantile, col=quantile), linewidth=0.8, position = pd)+
  xlab('NDVI Exposure Buffer Radius')+ ylab("Estimate and 95% CI")+ 
  
  ### Adjust ylim for each figure ###
  ylim(min(figure1$Lower_CI),max(figure1$Upper_CI)) + 
  
  #This line divides the graph in 4 according to time of measurement
  facet_wrap(~sample,strip.position="left",nrow=9,scales = "free_y")+
  geom_hline(yintercept =0, linetype=1)+
  theme(plot.title=element_text(size=16,face="bold"),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_text(face="bold"),
        axis.title=element_text(size=12,face="bold"),
        strip.text.y = element_text(hjust=0,vjust = 1,angle=180,face="bold"))+
  theme_bw()+
  guides(col=guide_legend(ncol=2))+
  theme(legend.position="bottom", legend.key.width=unit(1,"in"),legend.title = element_blank(),legend.text = element_text(colour="black", size = 11))  
```

```{r, Export}
if(iqr){
  out_path <- out_dir
}else{
  out_path <- paste0(sup_dir, 'sup_')
}

outname <- case_when(outcome == 'pss_score' ~ 'figure1',
                     outcome == 'b_mdi_score' ~ 'figure2') %>%
  paste0(out_path, ., '.png')
ggsave(outname, device = "png", width = 9, height = 6, units = "in", dpi = 320)
```
