---
title: "sensitivity"
author: "Cam Reimer"
date: "2024-01-09"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(labelled)
library(tidyr)
library(kableExtra)

source("analysis_functions.R")
load("C:/Users/camer/OneDrive/Documents/SPH/PRESTO/data/data_processed.RData")
load("C:/Users/camer/OneDrive/Documents/SPH/PRESTO/data/sensitivity_data.RData")
```

# Attempt Time at Study Entry 
```{r, Attempt Time: PSS}
#set up model runs 
x <- c("ageatqstn", "b_race_ethnic_census", "b_educ", "b_income", "b_totalmet", "ct_HHinc", "ct_lths")
models <- list(x[1:2], x[1:5], x[1:7]) #Model 1, 2, and 3
buffers <- c(100)                      #pick one buffer radius for this analysis
ndvi_measures <- c("amax", "smax", "smean")
outcome <- "pss_score"
iqr = TRUE              # Use NDVI IQR?
sig_figs = 2            # Significant digits in table output

# <3 cycles 
pss_3cycles <- data.frame()
for(i in 1:length(models)){
  for(j in 1:length(ndvi_measures)){
    pss_3cycles[i,j] <- lmfull_processed(data=cycles_3, y=outcome, buffers=buffers, x=models[[i]], 
                                         ndvi_measure=ndvi_measures[j], sig_figs = sig_figs, iqr = iqr)
  }
}
colnames(pss_3cycles) <- c("Annual Max", "Seasonal Max", "Seasonal Mean")
rownames(pss_3cycles) <- c("(<3) Model 1", "(<3) Model 2", "(<3) Model 3")

# <6 cycles 
pss_6cycles <- data.frame()
for(i in 1:length(models)){
  for(j in 1:length(ndvi_measures)){
    pss_6cycles[i,j] <- lmfull_processed(data=cycles_6, y=outcome, buffers=buffers, x=models[[i]], ndvi_measure=ndvi_measures[j],
                                         sig_figs = sig_figs, iqr = iqr)
  }
}
colnames(pss_6cycles) <- c("Annual Max", "Seasonal Max", "Seasonal Mean")
rownames(pss_6cycles) <- c("(<6) Model 1", "(<6) Model 2", "(<6) Model 3")

# Create table
pss_cycles <- rbind(pss_3cycles, pss_6cycles)

kbl(pss_cycles, caption = paste0(buffers[1],"m NDVI Buffer - PSS")) %>%
  kable_paper("striped", full_width = F) %>%
  pack_rows("<3 cycles", 1, 3) %>%
  pack_rows("<6 cycles", 4, 6) 
```

```{r, Attempt Time: MDI}
#set up model runs 
x <- c("ageatqstn", "b_race_ethnic_census", "b_educ", "b_income", "b_totalmet", "ct_HHinc", "ct_lths")
models <- list(x[1:2], x[1:5], x[1:7]) #Model 1, 2, and 3
buffers <- c(100)                      #pick one buffer radius for this analysis
ndvi_measures <- c("amax", "smax", "smean")
outcome <- "b_mdi_score"
iqr = TRUE              # Use NDVI IQR?
sig_figs = 2            # Significant digits in table output

# <3 cycles 
mdi_3cycles <- data.frame()
for(i in 1:length(models)){
  for(j in 1:length(ndvi_measures)){
    mdi_3cycles[i,j] <- lmfull_processed(data=cycles_3, y=outcome, buffers=buffers, x=models[[i]], ndvi_measure=ndvi_measures[j],
                                         sig_figs = sig_figs, iqr = iqr)
  }
}
colnames(mdi_3cycles) <- c("Annual Max", "Seasonal Max", "Seasonal Mean")
rownames(mdi_3cycles) <- c("(<3) Model 1", "(<3) Model 2", "(<3) Model 3")

# <6 cycles 
mdi_6cycles <- data.frame()
for(i in 1:length(models)){
  for(j in 1:length(ndvi_measures)){
    mdi_6cycles[i,j] <- lmfull_processed(data=cycles_6, y=outcome, buffers=buffers, x=models[[i]], ndvi_measure=ndvi_measures[j],
                                         sig_figs = sig_figs, iqr = iqr)
  }
}
colnames(mdi_6cycles) <- c("Annual Max", "Seasonal Max", "Seasonal Mean")
rownames(mdi_6cycles) <- c("(<6) Model 1", "(<6) Model 2", "(<6) Model 3")

# Create table
mdi_cycles <- rbind(mdi_3cycles, mdi_6cycles)

kbl(mdi_cycles, caption = paste0(buffers[1],"m NDVI Buffer - MDI")) %>%
  kable_paper("striped", full_width = F) %>%
  pack_rows("<3 cycles", 1, 3) %>%
  pack_rows("<6 cycles", 4, 6) 
```

# Parity 
```{r, Parity: PSS}
#set up model runs 
x <- c("ageatqstn", "b_race_ethnic_census", "b_educ", "b_income", "b_totalmet", "ct_HHinc", "ct_lths")
models <- list(x[1:2], x[1:5], x[1:7]) #Model 1, 2, and 3
buffers <- c(100)                      #pick one buffer radius for this analysis
ndvi_measures <- c("amax", "smax", "smean")
outcome <- "pss_score"
iqr = TRUE              # Use NDVI IQR?
sig_figs = 2            # Significant digits in table output

# <3 cycles 
pss_parous <- data.frame()
for(i in 1:length(models)){
  for(j in 1:length(ndvi_measures)){
    pss_parous[i,j] <- lmfull_processed(data=parous, y=outcome, buffers=buffers, x=models[[i]], ndvi_measure=ndvi_measures[j],
                                        sig_figs = sig_figs, iqr = iqr)
  }
}
colnames(pss_parous) <- c("Annual Max", "Seasonal Max", "Seasonal Mean")
rownames(pss_parous) <- c("(parous) Model 1", "(parous) Model 2", "(parous) Model 3")

# <6 cycles 
pss_nulli <- data.frame()
for(i in 1:length(models)){
  for(j in 1:length(ndvi_measures)){
    pss_nulli[i,j] <- lmfull_processed(data=nulliparous, y=outcome, buffers=buffers, x=models[[i]],
                                       ndvi_measure=ndvi_measures[j], sig_figs = sig_figs, iqr = iqr)
  }
}
colnames(pss_nulli) <- c("Annual Max", "Seasonal Max", "Seasonal Mean")
rownames(pss_nulli) <- c("(nulli) Model 1", "(nulliparous) Model 2", "(nulliparous) Model 3")

# Create table
pss_parity <- rbind(pss_parous, pss_nulli)

kbl(pss_parity, caption = paste0(buffers[1],"m NDVI Buffer - PSS")) %>%
  kable_paper("striped", full_width = F) %>%
  pack_rows("Parous", 1, 3) %>%
  pack_rows("<Nulliparous", 4, 6) 
```

```{r, Parity: MDI}
#set up model runs 
x <- c("ageatqstn", "b_race_ethnic_census", "b_educ", "b_income", "b_totalmet", "ct_HHinc", "ct_lths")
models <- list(x[1:2], x[1:5], x[1:7]) #Model 1, 2, and 3
buffers <- c(100)                      #pick one buffer radius for this analysis
ndvi_measures <- c("amax", "smax", "smean")
outcome <- "b_mdi_score"
iqr = TRUE              # Use NDVI IQR?
sig_figs = 2            # Significant digits in table output

# <3 cycles 
mdi_parous <- data.frame()
for(i in 1:length(models)){
  for(j in 1:length(ndvi_measures)){
    mdi_parous[i,j] <- lmfull_processed(data=parous, y=outcome, buffers=buffers, x=models[[i]], ndvi_measure=ndvi_measures[j], 
                                        sig_figs = sig_figs, iqr = iqr)
  }
}
colnames(mdi_parous) <- c("Annual Max", "Seasonal Max", "Seasonal Mean")
rownames(mdi_parous) <- c("(parous) Model 1", "(parous) Model 2", "(parous) Model 3")

# <6 cycles 
mdi_nulli <- data.frame()
for(i in 1:length(models)){
  for(j in 1:length(ndvi_measures)){
    mdi_nulli[i,j] <- lmfull_processed(data=nulliparous, y=outcome, buffers=buffers, x=models[[i]],
                                       ndvi_measure=ndvi_measures[j], sig_figs = sig_figs, iqr = iqr)
  }
}
colnames(mdi_nulli) <- c("Annual Max", "Seasonal Max", "Seasonal Mean")
rownames(mdi_nulli) <- c("(nulliparous) Model 1", "(nulliparous) Model 2", "(nulliparous) Model 3")

# Create table
mdi_parity <- rbind(mdi_parous, mdi_nulli)

kbl(mdi_parity, caption = paste0(buffers[1],"m NDVI Buffer - MDI")) %>%
  kable_paper("striped", full_width = F) %>%
  pack_rows("Parous", 1, 3) %>%
  pack_rows("Nulliparous", 4, 6) 
```

# Exercise 
```{r, Excluding Exercise}
############# INPUTS ###########################################################
data <- data            # Chose data (or subset of data) for this analysis 
buffers <- c(100)       # Pick one buffer radius for this analysis
iqr = TRUE              # Use NDVI IQR?
sig_figs = 2            # Significant digits in table output
################################################################################

# set up model runs 
x <- c("ageatqstn", "b_race_ethnic_census", "b_educ", "b_income", "ct_HHinc", "ct_lths")
models <- list(x[1:2], x[1:4], x[1:6]) #Model 1, 2, and 3
ndvi_measures <- c("amax", "smax", "smean")

# PSS score 
outcome <- "pss_score"
pss <- data.frame()
    #loop through models 
for(i in 1:length(models)){
    #loop through NDVI measures 
  for(j in 1:length(ndvi_measures)){
    pss[i,j] <- lmfull_processed(data = data, y = outcome, buffers = buffers, x = models[[i]], ndvi_measure = ndvi_measures[j], 
                                 sig_figs = sig_figs, iqr = iqr)
  }
}
colnames(pss) <- c("Annual Max", "Seasonal Max", "Seasonal Mean")
rownames(pss) <- c("PSS - Model 1", "PSS - Model 2", "PSS - Model 3")

#MDI score
outcome <- "b_mdi_score"
mdi <- data.frame(ncol = length(ndvi_measures), nrow = (length(models)))
for(i in 1:length(models)){
  for(j in 1:length(ndvi_measures)){
    mdi[i,j] <- lmfull_processed(data = data, y = outcome, buffers = buffers, x = models[[i]], ndvi_measure=ndvi_measures[j], 
                                 sig_figs = sig_figs, iqr = iqr)
  }
}
colnames(mdi) <- c("Annual Max", "Seasonal Max", "Seasonal Mean")
rownames(mdi) <- c("MDI - Model 1", "MDI - Model 2", "MDI - Model 3")

full <- rbind(pss, mdi)

kbl(full, caption = paste0(buffers[1],"m NDVI Buffer")) %>%
  kable_paper("striped", full_width = F) %>%
  pack_rows("PSS", 1, 3) %>%
  pack_rows("MDI", 4, 6) 
```

# Export 
```{r, Export}
sens_pss_table2 <- rbind(pss_cycles, pss_parity)
sens_mdi_table2 <- rbind(mdi_cycles, mdi_parity)

write.csv(sens_pss_table2, file = "C:/Users/camer/OneDrive/Documents/SPH/PRESTO/sensitivity/sens_pss_table2.csv")
write.csv(sens_mdi_table2, file = "C:/Users/camer/OneDrive/Documents/SPH/PRESTO/sensitivity/sens_mdi_table2.csv")
write.csv(full, file = "C:/Users/camer/OneDrive/Documents/SPH/PRESTO/sensitivity/noexercise_table2.csv")

```