---
title: "splines"
author: "Cam Reimer"
date: "2023-08-10"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
library(lubridate)
library(dplyr)
library(tidyr)
library(labelled)
library(mgcv)
library(scales)

load("C:/Users/camer/OneDrive/Documents/SPH/PRESTO/data/data_processed.RData")
```


```{r Create Figure for Supplement}
df <- imputed

spline1 <- gam(pss_score~ s(ndvi_100_smean, fx=TRUE, k=3) + ageatqstn + b_race_ethnic_census + b_educ + b_income + season + ct_HHinc + ct_lths , data = df, na.action=na.omit )
spline2 <- gam(b_mdi_score~ s(ndvi_100_smean, fx=TRUE, k=3) + ageatqstn + b_race_ethnic_census + b_educ + b_income + season + ct_HHinc + ct_lths , data = df, na.action=na.omit )

ylim1 <- c(-1,1)
xlim1 <- c(0,1)
a <- 0.6

png("C:/Users/camer/OneDrive/Documents/SPH/PRESTO/supplementary/splines.png", 
    width = 9, height = 6, units = 'in', pointsize = 12, res = 300)
par(mfrow=c(1,2))

plot(NA, xlim = xlim1, ylim = ylim1, axes = FALSE, ylab = '', xlab = '')
abline(h=0, lty = 3, col = alpha("grey", a))
par(new = TRUE)
plot(spline1, las=1, ylab="PSS Score", xlab= "NDVI", ylim = ylim1, xlim = xlim1)

legend("topright", c("Spline", "95%CI"), lty=1:2, box.lty=1, cex=0.9)
#mtext ("Full Sample", side=3, line=0.4, adj=1.85, cex=1.2)
text(0.865, 0.745, paste0("p-value: ", round(summary(spline1)$s.table[4], 3)), cex = 0.8)


plot(NA, xlim = xlim1, ylim = ylim1, axes = FALSE, ylab = '', xlab = '')
abline(h=0, lty = 3, col = alpha("grey", a))
par(new = TRUE)
plot(spline2, las=1, ylab="MDI Score", xlab= "NDVI", ylim = ylim1, xlim = xlim1)

legend("topright", c("Spline", "95%CI"), lty=1:2, box.lty=1, cex=0.9)
text(0.865, 0.745, paste0("p-value: ", round(summary(spline2)$s.table[4], 3)), cex = 0.8)

dev.off()
```

```{r Full sample spline for viz }
df <- imputed

spline1 <- gam(pss_score~ s(ndvi_100_smean, fx=TRUE, k=3) + ageatqstn + b_race_ethnic_census + b_educ + b_income + season + ct_HHinc + ct_lths , data = df, na.action=na.omit )
spline2 <- gam(b_mdi_score~ s(ndvi_100_smean, fx=TRUE, k=3) + ageatqstn + b_race_ethnic_census + b_educ + b_income + season + ct_HHinc + ct_lths , data = df, na.action=na.omit )

ylim1 <- c(-1,1)
xlim1 <- c(0,1)
a <- 0.6

par(mfrow=c(1,2))

plot(NA, xlim = xlim1, ylim = ylim1, axes = FALSE, ylab = '', xlab = '')
abline(h=0, lty = 3, col = alpha("grey", a))
par(new = TRUE)
plot(spline1, las=1, ylab="PSS Score", xlab= "NDVI", ylim = ylim1, xlim = xlim1)

legend("topright", c("Spline", "95%CI"), lty=1:2, box.lty=1, cex=0.9)
mtext ("Full Sample", side=3, line=0.4, adj=1.85, cex=1.2)
text(0.81, 0.635, paste0("p-value: ", round(summary(spline1)$s.table[4], 3)), cex = 0.8)


plot(NA, xlim = xlim1, ylim = ylim1, axes = FALSE, ylab = '', xlab = '')
abline(h=0, lty = 3, col = alpha("grey", a))
par(new = TRUE)
plot(spline2, las=1, ylab="MDI Score", xlab= "NDVI", ylim = ylim1, xlim = xlim1)

legend("topright", c("Spline", "95%CI"), lty=1:2, box.lty=1, cex=0.9)
text(0.81, 0.635, paste0("p-value: ", round(summary(spline2)$s.table[4], 3)), cex = 0.8)
```

```{r Stratified }
df <- NSES1_urban

spline1 <- gam(pss_score~ s(ndvi_100_smean, fx=TRUE, k=3) + ageatqstn + b_race_ethnic_census + b_educ + b_income + season + ct_lths , data = df, na.action=na.omit )
spline2 <- gam(b_mdi_score~ s(ndvi_100_smean, fx=TRUE, k=3) + ageatqstn + b_race_ethnic_census + b_educ + b_income + season + ct_lths , data = df, na.action=na.omit )

ylim1 <- c(-1.5,1.5)
xlim1 <- c(0,1)
a <- 0.6

par(mfrow=c(1,2))

plot(NA, xlim = xlim1, ylim = ylim1, axes = FALSE, ylab = '', xlab = '')
mtext("1st NSES Quantile, Urban Participants", side=3, line=0.4, adj=-1.3, cex=1.2)
abline(h=0, lty = 3, col = alpha("grey", a))
par(new = TRUE)
plot(spline1, las=1, ylab="PSS Score", xlab= "NDVI", ylim = ylim1, xlim = xlim1)

legend("topright", c("Spline", "95%CI"), lty=1:2, box.lty=1, cex=0.9)
text(0.81, 0.95, paste0("p-value: ", round(summary(spline1)$s.table[4], 3)), cex = 0.8)


plot(NA, xlim = xlim1, ylim = ylim1, axes = FALSE, ylab = '', xlab = '')
abline(h=0, lty = 3, col = alpha("grey", a))
par(new = TRUE)
plot(spline2, las=1, ylab="MDI Score", xlab= "NDVI", ylim = ylim1, xlim = xlim1)

legend("topright", c("Spline", "95%CI"), lty=1:2, box.lty=1, cex=0.9)
text(0.81, 0.95, paste0("p-value: ", round(summary(spline2)$s.table[4], 3)), cex = 0.8)
```

```{r Stratified }
df <- NSES3_urban

spline1 <- gam(pss_score~ s(ndvi_100_smean, fx=TRUE, k=3) + ageatqstn + b_race_ethnic_census + b_educ + b_income + season + ct_lths , data = df, na.action=na.omit )
spline2 <- gam(b_mdi_score~ s(ndvi_100_smean, fx=TRUE, k=3) + ageatqstn + b_race_ethnic_census + b_educ + b_income + season  + ct_lths , data = df, na.action=na.omit )

ylim1 <- c(-1.0,1.5)
xlim1 <- c(0,1)
a <- 0.6

par(mfrow=c(1,2))

plot(NA, xlim = xlim1, ylim = ylim1, axes = FALSE, ylab = '', xlab = '')
mtext("3rd NSES Quantile, Urban Participants", side=3, line=0.4, adj=-1.3, cex=1.2)
abline(h=0, lty = 3, col = alpha("grey", a))
par(new = TRUE)
plot(spline1, las=1, ylab="PSS Score", xlab= "NDVI", ylim = ylim1, xlim = xlim1)

legend("topright", c("Spline", "95%CI"), lty=1:2, box.lty=1, cex=0.9)
text(0.81, 1.05, paste0("p-value: ", round(summary(spline1)$s.table[4], 3)), cex = 0.8)


plot(NA, xlim = xlim1, ylim = ylim1, axes = FALSE, ylab = '', xlab = '')
abline(h=0, lty = 3, col = alpha("grey", a))
par(new = TRUE)
plot(spline2, las=1, ylab="MDI Score", xlab= "NDVI", ylim = ylim1, xlim = xlim1)

legend("topright", c("Spline", "95%CI"), lty=1:2, box.lty=1, cex=0.9)
text(0.81, 1.05, paste0("p-value: ", round(summary(spline2)$s.table[4], 3)), cex = 0.8)
```



