---
title: "table2"
author: "Cam Reimer"
date: "2/06/2023"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(labelled)
library(tidyr)
library(kableExtra)

source("analysis_functions.R")
load("C:/Users/camer/OneDrive/Documents/SPH/PRESTO/data/data_processed.RData")
```

```{r, Run Models}
############# INPUTS ###########################################################
data <- data            # Chose data (or subset of data) for this analysis 
buffers <- c(100)       # Pick one buffer radius for this analysis
iqr <- TRUE              # Use NDVI IQR?
sig_figs <- 2            # Significant digits in table output
outpath <- "C:/Users/camer/OneDrive/Documents/SPH/PRESTO/figures/"
supplementary_outpath <- "C:/Users/camer/OneDrive/Documents/SPH/PRESTO/supplementary/"
################################################################################

# set up model runs 
x <- c("ageatqstn", "b_race_ethnic_census", "b_educ", "b_income", "b_totalmet", "ct_HHinc", "ct_lths")
models <- list(x[1:2], x[1:5], x[1:7]) #Model 1, 2, and 3
ndvi_measures <- c("amax", "smax", "smean")

# PSS score 
outcome <- "pss_score"
pss <- data.frame()
    #loop through models 
for(i in 1:length(models)){
    #loop through NDVI measures 
  for(j in 1:length(ndvi_measures)){
    pss[i,j] <- lmfull_processed(data = data, y = outcome, buffers = buffers, x = models[[i]], ndvi_measure = ndvi_measures[j], 
                                 sig_figs = sig_figs, iqr = iqr)
  }
}
colnames(pss) <- c("Annual Max", "Seasonal Max", "Seasonal Mean")
rownames(pss) <- c("PSS - Model 1", "PSS - Model 2", "PSS - Model 3")

#MDI score
outcome <- "b_mdi_score"
mdi <- data.frame(ncol = length(ndvi_measures), nrow = (length(models)))
for(i in 1:length(models)){
  for(j in 1:length(ndvi_measures)){
    mdi[i,j] <- lmfull_processed(data = data, y = outcome, buffers = buffers, x = models[[i]], ndvi_measure=ndvi_measures[j], 
                                 sig_figs = sig_figs, iqr = iqr)
  }
}
colnames(mdi) <- c("Annual Max", "Seasonal Max", "Seasonal Mean")
rownames(mdi) <- c("MDI - Model 1", "MDI - Model 2", "MDI - Model 3")
```

```{r, Create Table}
full <- rbind(pss, mdi)

kbl(full, caption = paste0(buffers[1],"m NDVI Buffer")) %>%
  kable_paper("striped", full_width = F) %>%
  pack_rows("PSS", 1, 3) %>%
  pack_rows("MDI", 4, 6) 
```

```{r, Export}
if(iqr){
  write.csv(full, 
            paste0(outpath, "table2_", buffers[1], "m.csv"))
}else{
  write.csv(full, 
            paste0(supplementary_outpath, "NDVInotIQR_", buffers[1], "m_table2.csv"))
}
```
